// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/aprsweb/aprsweb.proto

package aprsweb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// An APRS check-in type
type CheckinType int32

const (
	CheckinType_POSITION         CheckinType = 0
	CheckinType_DIRECTIONFINDING CheckinType = 1
	CheckinType_OBJECT           CheckinType = 2
	CheckinType_WEATHER          CheckinType = 3
	CheckinType_TELEMETRY        CheckinType = 4
	CheckinType_MESSAGE          CheckinType = 5
	CheckinType_QUERY            CheckinType = 6
	CheckinType_RESPONSE         CheckinType = 7
	CheckinType_STATUS           CheckinType = 8
	CheckinType_OTHER            CheckinType = 9
)

var CheckinType_name = map[int32]string{
	0: "POSITION",
	1: "DIRECTIONFINDING",
	2: "OBJECT",
	3: "WEATHER",
	4: "TELEMETRY",
	5: "MESSAGE",
	6: "QUERY",
	7: "RESPONSE",
	8: "STATUS",
	9: "OTHER",
}

var CheckinType_value = map[string]int32{
	"POSITION":         0,
	"DIRECTIONFINDING": 1,
	"OBJECT":           2,
	"WEATHER":          3,
	"TELEMETRY":        4,
	"MESSAGE":          5,
	"QUERY":            6,
	"RESPONSE":         7,
	"STATUS":           8,
	"OTHER":            9,
}

func (x CheckinType) String() string {
	return proto.EnumName(CheckinType_name, int32(x))
}

func (CheckinType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{0}
}

// A Latitude/Longitude pair
type LatLng struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LatLng) Reset()         { *m = LatLng{} }
func (m *LatLng) String() string { return proto.CompactTextString(m) }
func (*LatLng) ProtoMessage()    {}
func (*LatLng) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{0}
}

func (m *LatLng) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LatLng.Unmarshal(m, b)
}
func (m *LatLng) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LatLng.Marshal(b, m, deterministic)
}
func (m *LatLng) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LatLng.Merge(m, src)
}
func (m *LatLng) XXX_Size() int {
	return xxx_messageInfo_LatLng.Size(m)
}
func (m *LatLng) XXX_DiscardUnknown() {
	xxx_messageInfo_LatLng.DiscardUnknown(m)
}

var xxx_messageInfo_LatLng proto.InternalMessageInfo

func (m *LatLng) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *LatLng) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

// A LocationCheckin is an APRS message containing a Location Checkin
type LocationCheckin struct {
	Timestamp            int64    `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Location             *LatLng  `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	IsMicE               bool     `protobuf:"varint,3,opt,name=IsMicE,proto3" json:"IsMicE,omitempty"`
	Speed                float64  `protobuf:"fixed64,4,opt,name=speed,proto3" json:"speed,omitempty"`
	RawGPS               string   `protobuf:"bytes,5,opt,name=RawGPS,proto3" json:"RawGPS,omitempty"`
	RawWX                string   `protobuf:"bytes,6,opt,name=RawWX,proto3" json:"RawWX,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LocationCheckin) Reset()         { *m = LocationCheckin{} }
func (m *LocationCheckin) String() string { return proto.CompactTextString(m) }
func (*LocationCheckin) ProtoMessage()    {}
func (*LocationCheckin) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{1}
}

func (m *LocationCheckin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LocationCheckin.Unmarshal(m, b)
}
func (m *LocationCheckin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LocationCheckin.Marshal(b, m, deterministic)
}
func (m *LocationCheckin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LocationCheckin.Merge(m, src)
}
func (m *LocationCheckin) XXX_Size() int {
	return xxx_messageInfo_LocationCheckin.Size(m)
}
func (m *LocationCheckin) XXX_DiscardUnknown() {
	xxx_messageInfo_LocationCheckin.DiscardUnknown(m)
}

var xxx_messageInfo_LocationCheckin proto.InternalMessageInfo

func (m *LocationCheckin) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *LocationCheckin) GetLocation() *LatLng {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *LocationCheckin) GetIsMicE() bool {
	if m != nil {
		return m.IsMicE
	}
	return false
}

func (m *LocationCheckin) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *LocationCheckin) GetRawGPS() string {
	if m != nil {
		return m.RawGPS
	}
	return ""
}

func (m *LocationCheckin) GetRawWX() string {
	if m != nil {
		return m.RawWX
	}
	return ""
}

// An APRS checkin
type Checkin struct {
	ReceivedDatetime int64       `protobuf:"varint,1,opt,name=received_datetime,json=receivedDatetime,proto3" json:"received_datetime,omitempty"`
	Type             CheckinType `protobuf:"varint,2,opt,name=type,proto3,enum=net.sfwem.aprsweb.CheckinType" json:"type,omitempty"`
	Source           string      `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Dest             string      `protobuf:"bytes,4,opt,name=dest,proto3" json:"dest,omitempty"`
	// Types that are valid to be assigned to Checkin:
	//	*Checkin_LocationCheckin
	Checkin              isCheckin_Checkin `protobuf_oneof:"checkin"`
	Comment              string            `protobuf:"bytes,999,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Checkin) Reset()         { *m = Checkin{} }
func (m *Checkin) String() string { return proto.CompactTextString(m) }
func (*Checkin) ProtoMessage()    {}
func (*Checkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{2}
}

func (m *Checkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Checkin.Unmarshal(m, b)
}
func (m *Checkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Checkin.Marshal(b, m, deterministic)
}
func (m *Checkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Checkin.Merge(m, src)
}
func (m *Checkin) XXX_Size() int {
	return xxx_messageInfo_Checkin.Size(m)
}
func (m *Checkin) XXX_DiscardUnknown() {
	xxx_messageInfo_Checkin.DiscardUnknown(m)
}

var xxx_messageInfo_Checkin proto.InternalMessageInfo

func (m *Checkin) GetReceivedDatetime() int64 {
	if m != nil {
		return m.ReceivedDatetime
	}
	return 0
}

func (m *Checkin) GetType() CheckinType {
	if m != nil {
		return m.Type
	}
	return CheckinType_POSITION
}

func (m *Checkin) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *Checkin) GetDest() string {
	if m != nil {
		return m.Dest
	}
	return ""
}

type isCheckin_Checkin interface {
	isCheckin_Checkin()
}

type Checkin_LocationCheckin struct {
	LocationCheckin *LocationCheckin `protobuf:"bytes,5,opt,name=LocationCheckin,proto3,oneof"`
}

func (*Checkin_LocationCheckin) isCheckin_Checkin() {}

func (m *Checkin) GetCheckin() isCheckin_Checkin {
	if m != nil {
		return m.Checkin
	}
	return nil
}

func (m *Checkin) GetLocationCheckin() *LocationCheckin {
	if x, ok := m.GetCheckin().(*Checkin_LocationCheckin); ok {
		return x.LocationCheckin
	}
	return nil
}

func (m *Checkin) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Checkin) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Checkin_LocationCheckin)(nil),
	}
}

// A GetCheckinsResponse is a list of Checkins
type GetCheckinsResponse struct {
	Checkins             []*Checkin `protobuf:"bytes,1,rep,name=Checkins,proto3" json:"Checkins,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetCheckinsResponse) Reset()         { *m = GetCheckinsResponse{} }
func (m *GetCheckinsResponse) String() string { return proto.CompactTextString(m) }
func (*GetCheckinsResponse) ProtoMessage()    {}
func (*GetCheckinsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{3}
}

func (m *GetCheckinsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCheckinsResponse.Unmarshal(m, b)
}
func (m *GetCheckinsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCheckinsResponse.Marshal(b, m, deterministic)
}
func (m *GetCheckinsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCheckinsResponse.Merge(m, src)
}
func (m *GetCheckinsResponse) XXX_Size() int {
	return xxx_messageInfo_GetCheckinsResponse.Size(m)
}
func (m *GetCheckinsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCheckinsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCheckinsResponse proto.InternalMessageInfo

func (m *GetCheckinsResponse) GetCheckins() []*Checkin {
	if m != nil {
		return m.Checkins
	}
	return nil
}

// A GetCheckinsRequest can specify how long to return checkins for
type GetCheckinsRequest struct {
	Since                int64    `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCheckinsRequest) Reset()         { *m = GetCheckinsRequest{} }
func (m *GetCheckinsRequest) String() string { return proto.CompactTextString(m) }
func (*GetCheckinsRequest) ProtoMessage()    {}
func (*GetCheckinsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_10b32125b7139f47, []int{4}
}

func (m *GetCheckinsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCheckinsRequest.Unmarshal(m, b)
}
func (m *GetCheckinsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCheckinsRequest.Marshal(b, m, deterministic)
}
func (m *GetCheckinsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCheckinsRequest.Merge(m, src)
}
func (m *GetCheckinsRequest) XXX_Size() int {
	return xxx_messageInfo_GetCheckinsRequest.Size(m)
}
func (m *GetCheckinsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCheckinsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCheckinsRequest proto.InternalMessageInfo

func (m *GetCheckinsRequest) GetSince() int64 {
	if m != nil {
		return m.Since
	}
	return 0
}

func init() {
	proto.RegisterEnum("net.sfwem.aprsweb.CheckinType", CheckinType_name, CheckinType_value)
	proto.RegisterType((*LatLng)(nil), "net.sfwem.aprsweb.LatLng")
	proto.RegisterType((*LocationCheckin)(nil), "net.sfwem.aprsweb.LocationCheckin")
	proto.RegisterType((*Checkin)(nil), "net.sfwem.aprsweb.Checkin")
	proto.RegisterType((*GetCheckinsResponse)(nil), "net.sfwem.aprsweb.GetCheckinsResponse")
	proto.RegisterType((*GetCheckinsRequest)(nil), "net.sfwem.aprsweb.GetCheckinsRequest")
}

func init() { proto.RegisterFile("rpc/aprsweb/aprsweb.proto", fileDescriptor_10b32125b7139f47) }

var fileDescriptor_10b32125b7139f47 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xeb, 0x8a, 0xd3, 0x40,
	0x18, 0xdd, 0xf4, 0x92, 0xcb, 0x17, 0x2f, 0xb3, 0xe3, 0x22, 0xd9, 0x45, 0xa4, 0x04, 0x94, 0xb2,
	0x42, 0x85, 0x88, 0xfe, 0xef, 0x65, 0x6c, 0x23, 0xbd, 0x39, 0xc9, 0x52, 0x57, 0x04, 0x49, 0xd3,
	0xb1, 0x06, 0xb7, 0x49, 0x6c, 0xa6, 0x96, 0x7d, 0x07, 0x7f, 0xfb, 0x40, 0xbe, 0x8c, 0xaf, 0x21,
	0x33, 0x49, 0xba, 0xbb, 0xb4, 0xe2, 0xaf, 0xf6, 0x7c, 0xdf, 0x99, 0x33, 0xe7, 0x9c, 0x21, 0x70,
	0xba, 0x4e, 0xc3, 0x97, 0x41, 0xba, 0xce, 0xb6, 0x6c, 0x5e, 0xfe, 0xb6, 0xd2, 0x75, 0xc2, 0x13,
	0x7c, 0x1c, 0x33, 0xde, 0xca, 0xbe, 0x6c, 0xd9, 0xaa, 0x55, 0x2c, 0xec, 0x0e, 0xa8, 0xc3, 0x80,
	0x0f, 0xe3, 0x25, 0x3e, 0x03, 0xfd, 0x2a, 0xe0, 0x11, 0xdf, 0x2c, 0x98, 0xa5, 0x34, 0x94, 0xa6,
	0x42, 0x77, 0x18, 0x3f, 0x01, 0xe3, 0x2a, 0x89, 0x97, 0xf9, 0xb2, 0x22, 0x97, 0x37, 0x03, 0xfb,
	0xb7, 0x02, 0x0f, 0x87, 0x49, 0x18, 0xf0, 0x28, 0x89, 0xbb, 0x5f, 0x59, 0xf8, 0x2d, 0x8a, 0xc5,
	0x09, 0x1e, 0xad, 0x58, 0xc6, 0x83, 0x55, 0x2a, 0xe5, 0xaa, 0xf4, 0x66, 0x80, 0x5f, 0x83, 0x5e,
	0x1e, 0x90, 0x72, 0xa6, 0x73, 0xda, 0xda, 0xf3, 0xd6, 0xca, 0x8d, 0xd1, 0x1d, 0x15, 0x3f, 0x06,
	0xd5, 0xcd, 0x46, 0x51, 0x48, 0xac, 0x6a, 0x43, 0x69, 0xea, 0xb4, 0x40, 0xf8, 0x04, 0xea, 0x59,
	0xca, 0xd8, 0xc2, 0xaa, 0x49, 0x6b, 0x39, 0x10, 0x6c, 0x1a, 0x6c, 0xfb, 0x53, 0xcf, 0xaa, 0x37,
	0x94, 0xa6, 0x41, 0x0b, 0x24, 0xd8, 0x34, 0xd8, 0xce, 0x3e, 0x58, 0xaa, 0x1c, 0xe7, 0xc0, 0xfe,
	0x59, 0x01, 0xad, 0x34, 0xff, 0x02, 0x8e, 0xd7, 0x2c, 0x64, 0xd1, 0x0f, 0xb6, 0xf8, 0xbc, 0x08,
	0x38, 0x13, 0xc6, 0x8b, 0x10, 0xa8, 0x5c, 0xf4, 0x8a, 0x39, 0x76, 0xa0, 0xc6, 0xaf, 0xd3, 0xbc,
	0x96, 0x07, 0xce, 0xd3, 0x03, 0x39, 0x0a, 0x59, 0xff, 0x3a, 0x65, 0x54, 0x72, 0x85, 0xb5, 0x2c,
	0xd9, 0xac, 0x43, 0x26, 0x83, 0x18, 0xb4, 0x40, 0x18, 0x43, 0x6d, 0xc1, 0x32, 0x2e, 0x73, 0x18,
	0x54, 0xfe, 0xc7, 0xe3, 0xbd, 0x72, 0x65, 0x1e, 0xd3, 0xb1, 0x0f, 0x55, 0x76, 0x97, 0x39, 0x38,
	0xa2, 0x7b, 0x2f, 0x73, 0x0a, 0x5a, 0x98, 0xac, 0x56, 0x2c, 0xe6, 0xd6, 0x1f, 0x4d, 0xde, 0x53,
	0xe2, 0x8e, 0x01, 0x5a, 0x98, 0xb3, 0xec, 0x11, 0x3c, 0xea, 0x33, 0x5e, 0x9c, 0xc9, 0x28, 0xcb,
	0xd2, 0x24, 0xce, 0x18, 0x7e, 0x03, 0x7a, 0x39, 0xb3, 0x94, 0x46, 0xb5, 0x69, 0x3a, 0x67, 0xff,
	0x0e, 0x4c, 0x77, 0x5c, 0xfb, 0x1c, 0xf0, 0x1d, 0xb9, 0xef, 0x1b, 0x11, 0x4d, 0xbc, 0x5b, 0x14,
	0x87, 0x65, 0xb7, 0x39, 0x38, 0xff, 0xa5, 0x80, 0x79, 0xab, 0x32, 0x7c, 0x0f, 0xf4, 0xe9, 0xc4,
	0x73, 0x7d, 0x77, 0x32, 0x46, 0x47, 0xf8, 0x04, 0x50, 0xcf, 0xa5, 0xa4, 0x2b, 0xe0, 0x5b, 0x77,
	0xdc, 0x73, 0xc7, 0x7d, 0xa4, 0x60, 0x00, 0x75, 0xd2, 0x79, 0x47, 0xba, 0x3e, 0xaa, 0x60, 0x13,
	0xb4, 0x19, 0x69, 0xfb, 0x03, 0x42, 0x51, 0x15, 0xdf, 0x07, 0xc3, 0x27, 0x43, 0x32, 0x22, 0x3e,
	0xbd, 0x44, 0x35, 0xb1, 0x1b, 0x11, 0xcf, 0x6b, 0xf7, 0x09, 0xaa, 0x63, 0x03, 0xea, 0xef, 0x2f,
	0x08, 0xbd, 0x44, 0xaa, 0xb8, 0x83, 0x12, 0x6f, 0x3a, 0x19, 0x7b, 0x04, 0x69, 0x42, 0xcd, 0xf3,
	0xdb, 0xfe, 0x85, 0x87, 0x74, 0x41, 0x9a, 0x48, 0x2d, 0xc3, 0x59, 0x82, 0xd6, 0x9e, 0x52, 0x6f,
	0xc6, 0xe6, 0xf8, 0x13, 0x98, 0xb7, 0xf2, 0xe0, 0x67, 0x07, 0x4a, 0xd8, 0xcf, 0x7b, 0xf6, 0xfc,
	0x7f, 0xb4, 0xbc, 0xe5, 0x8e, 0x39, 0xa8, 0x7c, 0xd4, 0x0a, 0xc2, 0x5c, 0x95, 0xdf, 0xee, 0xab,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0x12, 0x68, 0x60, 0xd8, 0x03, 0x00, 0x00,
}
